[package]
name = "cpr_gameboy"
description = "A easy-to-integrate gameboy emulation library"
version = "0.1.0"
edition = "2021"
authors = ["Wouter de Bruijn <wouter@wutru.io>"]
homepage = "https://github.com/cloone8/cpr_gameboy"
repository = "https://github.com/cloone8/cpr_gameboy"
license = "MPL-2.0"
tags = ["gameboy", "emulation", "game", "library"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
