[workspace]
resolver = "2"
members = [
    "ruboy",
    "ruboy_lib"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Wouter de Bruijn <wouter@wutru.io>"]
homepage = "https://github.com/cloone8/cpr_gameboy"
repository = "https://github.com/cloone8/cpr_gameboy"
license = "MPL-2.0"
keywords = ["gameboy", "emulation", "game", "library"]
categories = ["emulators"]

[workspace.dependencies]
ruboy_lib = { path = "ruboy_lib", version = "0.1.0" }
static_assertions = "1.1.0"
cfg-if = "1.0.0"
log = "0.4.21"
simplelog = "0.12.2"
